services:
  postgres:
    image: 'postgres:latest'
    environment:
      - 'POSTGRES_DB=goatcrypterdb'
      - 'POSTGRES_PASSWORD=password'
      - 'POSTGRES_USER=watermelon'
    ports:
      - '5432:5432'